[package]
name = "did"
version = "3.0.0"
description = "A motoko library for working with Decentralized Identifiers (DIDs)"
repository = "https://github.com/edjcase/motoko_did"
keywords = ["did", "decentralized", "identifiers", "ipld", "atproto"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"multiformats@2" = "2.1.0"
"url-kit@3" = "3.0.0"
"buffer@0" = "0.1.0"

[dev-dependencies]
test = "2.1.1"
