[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/edjcase/"
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.14.13"
new-base = "0.4.0"
multiformats = "0.0.3"

[dev-dependencies]
test = "2.1.1"
