[package]
name = "did"
version = "1.1.1"
description = "A motoko library for working with Decentralized Identifiers (DIDs)"
repository = "https://github.com/edjcase/motoko_did"
keywords = ["did", "decentralized", "identifiers", "ipld", "atproto"]
license = "MIT"

[dependencies]
base = "0.14.14"
new-base = "0.4.0"
multiformats = "0.0.4"
url-kit = "0.0.9"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.14"
